apiVersion: v2
name: convoy
description: Self-hosted, real-time GitHub Actions pipeline visualizer for your whole organization.
type: application
version: 0.1.1
appVersion: '1.0.1'
home: https://github.com/juaniartal/convoy
sources:
  - https://github.com/juaniartal/convoy
maintainers:
  - name: Juan Ignacio Artal
    url: https://www.linkedin.com/in/juanignaciodev/
