{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convoy.secretName" . }}
  labels:
    {{- include "convoy.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_ID: {{ .Values.github.appId | quote }}
  PRIVATE_KEY: {{ .Values.github.privateKey | quote }}
  WEBHOOK_SECRET: {{ .Values.github.webhookSecret | quote }}
  {{- if .Values.apiKey }}
  CONVOY_API_KEY: {{ .Values.apiKey | quote }}
  {{- end }}
  {{- if .Values.oidc.issuerUrl }}
  CONVOY_OIDC_ISSUER_URL: {{ .Values.oidc.issuerUrl | quote }}
  CONVOY_OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  CONVOY_OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  CONVOY_OIDC_REDIRECT_URI: {{ .Values.oidc.redirectUri | quote }}
  {{- if .Values.oidc.buttonLabel }}
  CONVOY_OIDC_BUTTON_LABEL: {{ .Values.oidc.buttonLabel | quote }}
  {{- end }}
  {{- end }}
{{- end }}
